### ISSUE TITLE
average finish affected when drivers DNQ in one car and race in another

### ISSUE THREAD

**Issue by melon-person-18** [64Soft/NRatings.Client#26] opened 2021-12-13 23:03 UTC
I've been doing a 1991 Busch Series season for a bit now, and when I was rating the cars, a few drivers who DNQd a race in one car and then entered in another car (bought out a ride maybe?) were negatively affected in the results.

One example is how Bobby Labonte DNQd the first race in the #44, and instead drove the #94 which was qualified by Terry Labonte. If I exclude that race from the sample, Bobby's average finish is something close to what it should be (about 10.2). When I add back in that race, it somehow makes his average finish 22.6

The same thing happens with Jeff Burton in races 6 and 12 (Hickory and Charlotte), where he DNQd in the #99 car and raced in the #45 - his average finish is 22.1 instead of 17.0, which is what it should be.

I'm not entirely sure if this is applied universally across all series and seasons or if it's just some early seasons.

**Comment by 64Soft** [comment] 2021-12-28 23:05
Hi, sorry for the late reply. When you apply ratings you normally thave the option to map the drivers by name only or by the combination of number and name. If you use the latter then the rating will apply to the combo of car number and name. Your example uses data from this page: https://www.racing-reference.info/race-results/1991_Goody%27s_300/B/ and it says #94 Bobby Labonte on the results sheet, so that's the car you should have in your carset and have it mapped to #94 Bobby Labonte coming from the NRatings result mapping.

**Comment by ai-line-mod** [comment] 2021-12-29 05:19
I'm not sure if this is related, but I've noticed an error among drivers who have started with multiple numbers as well, usually with the result of the average finish dropping dramatically. For example, 1999 BGN Glen Allen, Jr. has an average finish of 24.8 (https://www.racing-reference.info/driver-season-stats/allengl01/1999/B/), while NRatings puts the average finish at 32. Likewise, 1996 NWC Jeremy Mayfield has an average finish of 24.5 (https://www.racing-reference.info/driver-season-stats/mayfije01/1996/W/), while NRatings puts the average finish at 27.3. This is with car mapping method "By Name Only" and selecting all races for a given year.

**Comment by ai-line-mod** [comment] 2021-12-29 05:45
Actually, trying to think through this, I see the pattern, but I have not been able to replicate the precise calculations the NRatings might be incorrectly performing. @melon-person-18 your hypothesis was close, but the conditions which cause this issue are as follows:

1. mapping method "By Name Only"
2. all races selected for a season (or at least some races selected where a driver raced under different numbers)
3. driver has completed year with different numbers
4. driver has at least one DNQ

Now that that's known, you can go to any season and find a driver that satisfies conditions 3 and 4 and you'll find that their average finish suffers (e.g. Dick Trickle in 1996 NWC, Ed Berrier 1999 BGN... these are quickly discovered looking at the years/series mentioned last post). If I can figure out exactly what the program is doing I'll follow up.

(One small note - I *think* these conditions cover the anomalies described. However while checking I noticed that e.g. 1996 NWC Todd Bodine, who raced three numbers, has a slightly different avgfn on RR than on NR; 21.5 and 21.6 respectively. He has no DNQ for that year. This might be due to rounding, though I'm unsure about this as often NR maps pretty directly to the stats as the appear on RR.)

**Comment by ai-line-mod** [comment] 2021-12-29 17:13
I believe I have identified the error, but not yet the cause in the code (likely related to DriverStats.cs?). My "One small note" is the key; what NR is doing is taking an average of averages for drivers with different starting numbers, rather than an average of ALL starts. Using 1996 NWC Jeremy Mayfield for example:

- 23 starts in #98 with an average finish of 22.086
- 7 starts in #37 with an average finish of 32.429

Averaging those two values gets you spot on for the value NR produces: 27.258. Whereas if you average ALL races despite the car number you get the appropriate avgfn of 24.5. This also holds true for average start.

The error in my above post is #4: drivers do not have to have a DNQ, but rather a driver with a DNQ is likely to be less consistent, resulting in larger variability between two or more avgfn by different starting number.

While I have yet to locate the logic in the code, my guess is that what is happening is that when mapping by Name Only, the program should determine the driver first (an aggregate of all starts by name despite number) and then determine the average start/finish rather than treat each number/name combination as different and then computing the averages.

**Comment by ai-line-mod** [comment] 2021-12-29 18:30
I found the code that performs the logic from race results here: https://github.com/64Soft/NRatings.Client/blob/main/src/NRatings.Client/Business/RealDataProcessor.cs

Line 502 a list called Stats is created which groups data by the Driver attribute from driverRaceDataList (presumably from RR):

                stats = (from s in stats
                         group s by s.Driver into gr
                         from s in gr
                         orderby gr.Average(s2 => s2.AvgFinish).Round(4) ascending
                         select new DriverStats

However my guess is `gr.Average(s2 => s2.AvgFinish).Round(4)` is creating an average (gr.Average) of an average (s2.AvgFinish) which is already defined on the previous list on line 417: `AvgFinish = gr.Average(drd2 => (int?)drd2.RaceResult.FinishPosition).Round(4)`.

I'm not sure if redefining the variables in each "if" list as they are done in the first list (starting line 409) would do the trick. In other words, both "if" lists (name only and driver only) duplicate the logic from lines 417-498. I suspect then each attribute which is an average is off then (most of them), for both the name mapping method and number. I don't know if this causes issues when taking the data from driverRaceDataList and grouping by Driver or Number only as I cannot see the data as it is before it goes through this process.

Also side question what's the (int?) doing on line 417 and why is it not there for other averages (e.g. start average)? Is it necessary?

**Comment by 64Soft** [comment] 2022-01-17 15:19
Closing this one as it will be further discussed in #30

**Closed by 64Soft** 2022-01-17 15:19 UTC
